### ISSUE TITLE
Database organisation

### ISSUE THREAD

**Issue by ChristianSch** [ChristianSch/ActivityLogger#2]
* local storage
* firebase

datagram needed for both types of databases.

see http://stackoverflow.com/questions/23715170/best-data-persistence-for-angularjs-javascript-apps-on-phonegap

**Comment by ecff12** [comment]
Ok,
 ich melde mich

2015-01-03 16:55 GMT+01:00 Christian Schulze <notifications@github.com>:

**Comment by ecff12** [comment]
getAllCompetition  Bug fix und gepush . Mal testen

2015-01-25 15:12 GMT+01:00 Christian Schulze <notifications@github.com>:

**Comment by ChristianSch** [comment]
Gibt immer noch null zurück. Da muss ein leeres array rauskommen, aber sonst scheint es zu gehen. Recursion error ist weg (bisher).
